import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import '@fortawesome/fontawesome-free/css/all.min.css'; // For FontAwesome
import 'bootstrap-icons/font/bootstrap-icons.css'; // For Bootstrap Icons
import Footer from "@/components/ui/footer";
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <div >
          <Header />
          {children}
          <Footer/> 
        </div>
      </body>
    </html>
  );
}
